.TH freealchemist 1 "28 Jun 2008"
.SH NAME
freealchemist \- Simpler figure block game
.PP
\fBFreeAlchemist\fP is a figure block game written in Python where you have to
connect blocks.
.PP
The three blocks connected with the same shape will be replaced by a block with
a different shape.
.RE
.SH AUTHOR
freealchemist was written by PDak <dak.linux@gmail.com>.
.PP
This manual page was written by Devid Antonio Filoni <d.filoni@ubuntu.com>,
for the Debian project (but may be used by others).
